#!/bin/bash

# Thumbnail Sizes
# x150
# x800
# x1080

printf "Scanning photos in folder $1 \n"
photos=$(find $1 -iname '*.JPG')
item_count=$(echo "$photos" | wc -l)
printf "Found $item_count items \n"
current_item_count=1

for photo in $photos
do
    printf "$current_item_count/$item_count : Generating $3 thumb for $photo \n"
    photo_dir=$2/$3/$(dirname $photo)
    mkdir -p $photo_dir
    mogrify -path $photo_dir -thumbnail $3 $photo
    current_item_count=$[current_item_count + 1]
done
